[package]
edition = "2021"
name = "dice_examples"
version = "0.0.0"

[dependencies]
allocative = { workspace = true }
anyhow = "1.0.65"
async-trait = "0.1.24"
derive_more = "0.99.3"
dupe = { workspace = true }
futures = "0.3"
gazebo = { workspace = true }
higher-order-closure = { workspace = true }
more_futures = { path = "../../shed/more_futures" }
ref-cast = "1.0.0"

dice = { path = "../dice" }

[dev-dependencies]
anyhow = "1.0.65"
cast = "0.2.3"
futures = "0.3"
paste = "1.0" # !
tokio = { version = "1.5", features = ["full"] }
