[package]
description = """
Code shared with Meta internal buck2 launcher.

Careful! The wrapper is not released as part of the regular buck version bumps,
meaning code changes here are not "atomically" updated.
"""
edition = "2021"
name = "buck2_wrapper_common"
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
anyhow = { workspace = true }
dupe = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
shlex = { workspace = true }
sysinfo = { workspace = true }
uuid = { workspace = true }

buck2_error = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

buck2_util = { workspace = true }
