[package]
name = "buck2_interpreter_tests"
version = "0.1.0"
edition = "2021"
description = "Tests for buck2_interpreter"

[dev-dependencies]
anyhow = { workspace = true }
indoc = { workspace = true }

buck2_interpreter = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
