[package]
authors = ["Facebook"]
description = "Derive macros for the Buck's buck2_build_api"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "buck2_build_api_derive"
version = "0.4.1"

[lib]
proc-macro = true

[dependencies]
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

gazebo = { workspace = true }

gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
gazebo_lint.version = "0.1"

[features]
# @oss-disable: default = ["gazebo_lint"]
