[package]
description = "Tests for buck2_action_impl"
edition = "2021"
name = "buck2_action_impl_tests"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
ctor = { workspace = true }
indoc = { workspace = true }
maplit = { workspace = true }

dupe = { workspace = true }
starlark = { workspace = true }

buck2_action_impl = { workspace = true }
buck2_anon_target = { workspace = true }
buck2_build_api = { workspace = true }
buck2_core = { workspace = true }
buck2_execute = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_node = { workspace = true }
