[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "more_futures"
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_wrapper_common = { workspace = true }
dupe = { workspace = true }
futures = "0.3"
once_cell = { workspace = true }
parking_lot = { workspace = true }
pin-project = "0.4"
slab = "0.4.7"
take_mut = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.5", features = ["full"] }
tracing = "0.1.22"

[dev-dependencies]
assert_matches = { workspace = true }
