[package]
description = "Similar to `internment` crate, but with interface and performance tweaks"
edition = "2021"
name = "static_interner"
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
dupe = { workspace = true }
equivalent = { workspace = true }
gazebo = { workspace = true }
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
gazebo_lint.version = "0.1"
lock_free_hashtable = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]
