[package]
description = "Similar to `internment` crate, but with interface and performance tweaks"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "static_interner"
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
dupe = { workspace = true }
equivalent = { workspace = true }
lock_free_hashtable = { workspace = true }
