[package]
authors = ["Meta"]
description = "Serialized datastructures for buck2_miniperf"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "buck2_miniperf_proto"
version = "0.1.0"

[dependencies]
dupe = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
