[package]
description = "Interprets build files and handles loading and interpreting extension files, and communicating this information to DICE"
edition = "2021"
name = "buck2_interpreter"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
fancy-regex = { workspace = true }
plist = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
gazebo_lint.version = "0.1"
more_futures = { path = "../../shed/more_futures" }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_util = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]

[dev-dependencies]
tempfile = { workspace = true }
