[package]
description = "e2e tests for DICE. Live in a separate crate for faster development."
edition = "2021"
name = "dice_tests"
publish = false
version = "0.0.0"

[dev-dependencies]
allocative = { workspace = true }
dupe = { workspace = true }
more_futures = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
parking_lot = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }

dice = { workspace = true }
