[package]
name = "buck2_error_derive"
version = "0.1.0"
edition = "2021"
description = """
Macros used by buck2_error
"""

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
