[package]
edition = "2021"
name = "buck2_common"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
chrono = { workspace = true }
compact_str = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
digest = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
globset = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
num_enum = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
ref-cast = { workspace = true }
regex = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
smallvec = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
cmp_any = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
more_futures = { workspace = true }
starlark_map = { workspace = true }

buck2_core = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_util = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }
tower = { workspace = true }
xattr = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
indoc = { workspace = true }
maplit = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
