[package]
edition = "2021"
license = { workspace = true }
name = "buck2_downward_api"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
