[package]
description = "Buck2 query language parser"
edition = "2021"
name = "buck2_query_parser"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
derive_more = { workspace = true }
enum-map = { workspace = true }
nom = { workspace = true }
structopt = { workspace = true }
thiserror = { workspace = true }

dupe = { workspace = true }
gazebo = { workspace = true }
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
gazebo_lint.version = "0.1"

buck2_util = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]
