[package]
description = "Buck2 query language parser"
edition = "2021"
name = "buck2_query_parser"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
derive_more = { workspace = true }
enum-map = { workspace = true }
nom = { workspace = true }
structopt = { workspace = true }

dupe = { workspace = true }
gazebo = { workspace = true }

buck2_error = { workspace = true }
buck2_util = { workspace = true }
