[package]
edition = "2021"
name = "buck2_core"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
assert_matches = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
compact_str = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
dunce = { workspace = true }
either = { workspace = true }
equivalent = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
hostname = { workspace = true }
indent_write = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
memchr = { workspace = true }
once_cell = { workspace = true }
os_str_bytes = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true }
ref-cast = { workspace = true }
regex = { workspace = true }
relative-path = { workspace = true }
sequence_trie = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
starlark_map = { workspace = true }
static_assertions = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
triomphe = { workspace = true }

allocative = { workspace = true }
cmp_any = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
gazebo_lint.version = "0.1"
internment_tweaks = { path = "../../shed/internment_tweaks" }
sorted_vector_map = { workspace = true }

buck2_data = { workspace = true }
buck2_util = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
common-path = { workspace = true }

[dev-dependencies]
maplit = { workspace = true }
serde_json = { workspace = true }
test-case = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]
