[package]
description = """
Library providing an `anyhow` inspired error type for buck2
"""
edition = "2021"
name = "buck2_error"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
derive_more = { workspace = true }
ref-cast = { workspace = true }
thiserror = { workspace = true }

allocative = { workspace = true }
dupe = { workspace = true }

buck2_error_derive = { workspace = true }
