[package]
edition = "2021"
name = "buck2_http"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-proxy = { workspace = true }
hyper-rustls = { workspace = true }
hyper-timeout = { workspace = true }
ipnetwork = { workspace = true }
pin-project = { workspace = true }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }
rustls-pemfile = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }

buck2_error = { workspace = true }

[target.'cfg(unix)'.dependencies]
hyper-unix-connector = { workspace = true }

[dev-dependencies]
httptest = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
tempfile = { workspace = true }
