[package]
name = "buck2_audit"
version = "0.1.0"
edition = "2021"
description = "Client side of `buck2 audit`"

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

dupe = { workspace = true }

buck2_client_ctx = { workspace = true }
buck2_cli_proto = { workspace = true }
