[package]
edition = "2021"
name = "read_dump"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }

dice = { path = "../dice" }
