[package]
description = "A library providing gRPC client for Bazel remote execution"
edition = "2021"
name = "re_grpc_proto"
version = "0.1.0"

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
buck2_protoc_dev = { workspace = true }
