name: Build and upload Buck2 binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: 'ubuntu-22.04'
            triple: 'aarch64-unknown-linux-gnu'
            cross: true
          - os: 'ubuntu-22.04'
            triple: 'aarch64-unknown-linux-musl'
            cross: true
          - os: 'ubuntu-22.04'
            triple: 'x86_64-unknown-linux-gnu'
          # - os: 'ubuntu-22.04'
          #   triple: 'x86_64-unknown-linux-musl' # Doesn't build
          - os: 'macos-12'
            triple: 'aarch64-apple-darwin'
          - os: 'macos-12'
            triple: 'x86_64-apple-darwin'
          - os: 'windows-2022'
            triple: 'x86_64-pc-windows-msvc'
    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target.os }}

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-01-24
          targets: ${{ matrix.target.triple }}

      - uses: actions-rs/install@v0.1
        if: matrix.target.cross
        with:
          crate: cross
          version: latest

      - name: Build
        shell: bash
        run: |
          if [ -n "${{ matrix.target.cross }}" ]; then
            CARGO=cross
          else
            CARGO=cargo
          fi

          $CARGO build --release --bin buck2 --target ${{ matrix.target.triple }}
          mkdir upload
          cp target/${{ matrix.target.triple }}/release/buck2* upload/

      - name: Upload (non-Windows)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: buck2-${{ matrix.target.triple }}
          path: upload/buck2

      - name: Upload (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: buck2-${{ matrix.target.triple }}
          path: upload/buck2.exe
